sudo: required

services:
    - docker

script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t philipsorst/php-testing:20-04-8-0 .
    - docker push philipsorst/php-testing:20-04-8-0
