sudo: required

services:
    - docker

script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t philipsorst/php-testing:18-04-7-4 .
    - docker push philipsorst/php-testing:18-04-7-4
